# Kubernetes
k8s_version: v1.3.7
flanneld_version: v0.5.3
service_ip_range: 10.3.0.0/24
k8s_service_ip: 10.3.0.1
dns_domain: cluster.local.
# enable_admission_controls: "NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota"
enable_admission_controls: []
log_level: 3
master_as_node: false

# Kubernetes addons列表, 空列表为不启用任何addon
enabled_addons: []

# Docker
docker_api_port: 2376

# flanneld
pod_network: 10.2.0.0/16
